### ISSUE TITLE
请问如何使用WCDB保存比较复杂的多层模型

### ISSUE THREAD

**Issue by xinluqi001** [wpCXY/WCDBDemo#1]
比如, 一个 Person 类, 包含了 age(int), name(NSString *),  numbers(NSArray *<Numbers *>)
里面这个 Numbers * 是另外一个类, 它里面又包含了其他属性 或者 其他类

这中模型嵌套的情况, 在WCDB中该如何去写?

**Comment by wpCXY** [comment]
思路一：将嵌套的模型分开保存到各自的表中，通过共用主键来关联起来(一对一)，或者通过保存子模型的主键来关联起来(一对多)。 
思路二：将嵌套的模型转换为json字符串来保存，取出后转换为模型。
